# Generated by Django 2.0.1 on 2018-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='totalAmountDonated',
            field=models.FloatField(default=0),
        ),
    ]
